<?php

require_once 'blog/om/BaseBlogs.php';


/**
 * Skeleton subclass for representing a row from the 'blogs' table.
 *
 * 
 *
 * This class was autogenerated by Propel on:
 *
 * Tue Dec  6 23:40:21 2005
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package blog
 */	
class Blogs extends BaseBlogs {

} // Blogs
