<?php
// This file generated by Propel convert-props target on Tue Dec  6 23:40:21 2005
// from XML runtime conf file ./projects/blog/runtime-conf.xml
return array (
  'log' => 
  array (
    'ident' => 'blog',
    'level' => '7',
  ),
  'propel' => 
  array (
    'datasources' => 
    array (
      'blog' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'phptype' => 'mysql',
          'hostspec' => 'localhost',
          'database' => 'blog',
          'username' => 'develop',
          'password' => 'develop',
        ),
      ),
      'default' => 'blog',
    ),
  ),
);
