production:
  host: 'localhost'
  dbname: 'testdb'
  user: 'user'
  pass: 'pass'
  
development:
  host: 'localhost'
  dbname: 'testdb'
  user: 'user'
  pass: 'pass'
  
unittest:
  host: 'localhost'
  dbname: 'testdb'
  user: 'user'
  pass: 'pass'
  